openapi: 3.0.0
info:
  title: Simple dashboard for PostgreSQL
  version: 0.0.1
  description: Collection of all available REST handlers
servers:
  - url: http://localhost:8001/api
tags:
  - name: cluster
    description: Everything related to Postgres cluster data
paths:
  /cluster/status:
    get:
      tags:
        - cluster
      summary: Get server current status
      operationId: GetStatus
      responses:
        "200":
          description: Server current status
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetStatusResponse"
              examples:
                success:
                  summary: Status received successfully
                  value:
                    user: postgres
                    database: postgres
                    connectionStatus: connected
                connection lost:
                  summary: Status with lost connection
                  value:
                    connectionStatus: disconnected
        "400":
          description: Request server status failed
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorBase"
  /cluster/connect:
    post:
      tags:
        - cluster
      summary: Connect to Postgres cluster
      description: Connect to Postgres cluster
      operationId: ClusterConnect
      requestBody:
        required: true
        description: Request's data payload
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ClusterConnectData"
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetStatusResponse"
        "422":
          description: Request data invalid
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RequestValidationError"
        "400":
          description: Connection attempt failed
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorBase"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorBase"
  /cluster/disconnect:
    post:
      tags:
        - cluster
      summary: Disconnect from Postgres cluster
      description: Disconnect from Postgres cluster
      operationId: ClusterDisconnect
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetStatusResponse"
        "400":
          description: Disconnection attempt failed
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorBase"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorBase"
  /cluster/version:
    get:
      tags:
        - cluster
      summary: Get detailed Postgres version info
      description: Get detailed Postgres version info
      operationId: PostgresVersion
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetPostgresVersionResponse"
        "400":
          description: Attempt failed
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorBase"
  /cluster/uptime:
    get:
      tags:
        - cluster
      summary: Get Postgres uptime info
      description: Get Postgres uptime info
      operationId: PostgresUptime
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetPostgresUptimeResponse"
        "400":
          description: Attempt failed
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorBase"
  /cluster/postmaster-settings:
    get:
      tags:
        - cluster
      summary: Get global cluster settings
      description: Returns some settings from pg_settings in the "postmaster" context.
      operationId: PostmasterSettings
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/GetPostgresPostmasterSettings"
                example:
                  configFile:
                    name: config_file
                    value: /Library/PostgreSQL/16/data/postgresql.conf
                    unit: ""
                    description: Sets the server's main configuration file
                  dataDirectory:
                    name: data_directory
                    value: /Library/PostgreSQL/16/data
                    unit: ""
                    description: Sets the server's data directory.
                  sharedBuffers:
                    name: shared_buffers
                    value: 256 MB
                    unit: 8kB
                    description: Sets the number of shared memory buffers used by the server.
                  walBuffers:
                    name: wal_buffers
                    value: 8 MB
                    unit: 8kB
                    description: Sets the number of disk-page buffers in shared memory for WAL.
                  maxConnections:
                    name: max_connections
                    value: "100"
                    unit: ""
                    description: Sets the maximum number of concurrent connections.
                  hbaFile:
                    name: hba_file
                    value: /Library/PostgreSQL/16/data/pg_hba.conf
                    unit: ""
                    description: Sets the server's "hba" configuration file.
                  walLevel:
                    name: wal_level
                    value: replica
                    unit: ""
                    description: Sets the level of information written to the WAL.
                  autovacuumMaxWorkers:
                    name: autovacuum_max_workers
                    value: "4"
                    unit: ""
                    description: Sets the maximum number of simultaneously running autovacuum worker
                      processes.
        "400":
          description: Attempt failed
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorBase"
  /cluster/databases-detailed:
    get:
      tags:
        - cluster
      summary: Get cluster databases
      description: Returns a list of all available databases with their details
      operationId: DatabasesDetailed
      parameters:
        - name: sort
          description: Field to sort by
          in: query
          required: false
          schema:
            type: string
            enum: [ size, connection ]
          x-oapi-codegen-extra-tags:
            validate: "omitempty,oneof=size connection"
        - name: order
          description: Sort direction
          in: query
          required: false
          schema:
            type: string
            enum: [ asc, desc ]
          x-oapi-codegen-extra-tags:
            validate: "omitempty,oneof=asc desc"
          # default: desc
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Database"
        "400":
          description: Attempt failed
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorBase"
        "422":
          description: Some query params are invalid
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RequestValidationError"
  /cluster/roles:
    get:
      tags:
        - cluster
      summary: Get available roles
      description: Returns a list of all available roles with their details
      operationId: Roles
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/RoleView"
        "400":
          description: Attempt failed
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorBase"
components:
  schemas:
    ErrorBase:
      type: object
      description: Error part that should be present in all errors
      required:
        - message
      properties:
        message:
          type: string
          example: something went wrong
    RequestValidationError:
      allOf:
        - $ref: "#/components/schemas/ErrorBase"
        - type: object
          properties:
            reason:
              type: string
              example: the body fields are invalid
          required:
            - reason
    ConnectionStatus:
      type: string
      description: Represents connection state between dashboard and postgres
      example: connected
      enum: [ connecting, connected, disconnected, error ]
      x-enum-varnames:
        - PgConnectionStatusConnecting,
        - PgConnectionStatusConnected,
        - PgConnectionStatusDisconnected,
        - PgConnectionStatusError,
    PostgresSetting:
      type: object
      description: Represents some columns from "pg_catalog.pg_settings"
      x-go-type: clusterEntities.Setting
      x-go-type-import:
        path: dashboard/api/internal/scopes/cluster/entities
        name: Setting
      x-go-type-name: clusterEntities.Setting
      required:
        - name
        - value
        - unit
        - description
      properties:
        name:
          type: string
          example: shared_buffers
        value:
          type: string
          example: "32768"
        unit:
          type: string
          example: 8kB
        description:
          type: string
          example: Sets the number of...
    Database:
      type: object
      description: Represents database entity from Postgres system catalog
      x-go-type: clusterEntities.DatabaseDetails
      x-go-type-import:
        path: dashboard/api/internal/scopes/cluster/entities
        name: DatabaseDetails
      x-go-type-name: clusterEntities.DatabaseDetails
      required:
        - id
        - name
        - owner
        - encoding
        - collate
        - ctype
        - isTemplate
        - allowConnections
        - connectionLimit
        - sizeBytes
        - sizePretty
        - totalConnections
      properties:
        id:
          type: string
          description: This is essentially a Postgres OID.
          example: "1"
        name:
          type: string
          example: postgres
        owner:
          type: string
          example: postgres
        encoding:
          type: string
          example: UTF8
        collate:
          type: string
          example: en_US.UTF-8
        ctype:
          type: string
          example: en_US.UTF-8
        isTemplate:
          type: boolean
          example: false
        allowConnections:
          type: boolean
          example: true
        connectionLimit:
          type: integer
          example: -1
        sizeBytes:
          type: integer
          example: 7746019
        sizePretty:
          type: string
          example: "6.4 MB"
        totalConnections:
          type: integer
          example: 3
    GetStatusResponse:
      type: object
      required:
        - connectionStatus
      properties:
        connectionStatus:
          $ref: "#/components/schemas/ConnectionStatus"
        user:
          nullable: true
          type: string
          example: postgres
        database:
          nullable: true
          type: string
          example: postgres
    ClusterConnectData:
      x-go-type: clusterEntities.AuthData
      x-go-type-import:
        path: dashboard/api/internal/scopes/cluster/entities
        name: clusterEntities
      x-go-type-name: clusterEntities.AuthData
      type: object
      required:
        - host
        - port
        - user
        - password
        - sslmode
      properties:
        host:
          type: string
          example: 127.0.0.1
        port:
          type: integer
          example: 5432
        user:
          type: string
          example: postgres
        password:
          type: string
          example: postgres
        database:
          type: string
          example: postgres
        sslmode:
          type: string
          example: ""
    GetPostgresVersionResponse:
      x-go-type: clusterEntities.PostgresVersion
      x-go-type-import:
        path: dashboard/api/internal/scopes/cluster/entities
        name: clusterEntities
      x-go-type-name: clusterEntities.PostgresVersion
      type: object
      required:
        - version
        - compiler
        - bitDepth
      properties:
        version:
          type: string
          example: PostgreSQL 15.3 on x86_64-pc-linux-gnu
        compiler:
          type: string
          example: compiled by gcc (Ubuntu 11.3.0) 11.3.0
        bitDepth:
          type: string
          example: 64-bit
    GetPostgresUptimeResponse:
      x-go-type: clusterEntities.PostgresUptime
      x-go-type-import:
        path: dashboard/api/internal/scopes/cluster/entities
        name: clusterEntities
      x-go-type-name: clusterEntities.PostgresUptime
      type: object
      description: Returns an ISO-8601 string with timezone
      required:
        - startedAt
      properties:
        startedAt:
          type: string
          example: 2025-12-05 13:45:06.746931+02
    GetPostgresPostmasterSettings:
      x-go-type: clusterEntities.PostmasterSettings
      x-go-type-import:
        path: dashboard/api/internal/scopes/cluster/entities
        name: PostmasterSettings
      x-go-type-name: clusterEntities.PostmasterSettings
      type: object
      description: Represents some settings from pg_settings in the "postmaster" context.
      required:
        - configFile
        - dataDirectory
        - sharedBuffers
        - walBuffers
        - maxConnections
        - hbaFile
        - walLevel
        - autovacuumMaxWorkers
      properties:
        configFile:
          $ref: "#/components/schemas/PostgresSetting"
        dataDirectory:
          $ref: "#/components/schemas/PostgresSetting"
        sharedBuffers:
          $ref: "#/components/schemas/PostgresSetting"
        walBuffers:
          $ref: "#/components/schemas/PostgresSetting"
        maxConnections:
          $ref: "#/components/schemas/PostgresSetting"
        hbaFile:
          $ref: "#/components/schemas/PostgresSetting"
        walLevel:
          $ref: "#/components/schemas/PostgresSetting"
        autovacuumMaxWorkers:
          $ref: "#/components/schemas/PostgresSetting"
    RoleAccessLevel:
      type: string
      description: Admin > Elevated > Standard > Limited
      enum:
        - admin
        - elevated
        - standard
        - limited
      x-go-type: clusterEntities.RoleAccessLevel
      x-go-type-import:
        path: dashboard/api/internal/scopes/cluster/entities
        name: clusterEntities
    RoleAttributes:
      type: string
      description: https://www.postgresql.org/docs/current/role-attributes.html#ROLE-ATTRIBUTES
      enum:
        - superuser
        - login
        - createRole
        - createDatabase
        - replication
      x-go-type: clusterEntities.RoleAttribute
      x-go-type-import:
        path: dashboard/api/internal/scopes/cluster/entities
        name: clusterEntities
    RoleView:
      type: object
      required:
        - id
        - name
        - isGroup
        - accessLevel
        - membership
        - attributes
      x-go-type: entities.RoleView
      x-go-type-import:
        path: dashboard/api/internal/scopes/cluster/entities
        name: clusterEntities
      properties:
        id:
          type: string
        name:
          type: string
        isGroup:
          type: boolean
        membership:
          type: array
          items:
            type: object
            required:
              - name
              - description
            properties:
              name:
                type: string
              description:
                type: string
        attributes:
          type: array
          items:
            $ref: "#/components/schemas/RoleAttributes"
        accessLevel:
          $ref: "#/components/schemas/RoleAccessLevel"
